name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment otherwise it will be automatically closed in 5 days'
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment otherwise it will be automatically closed in 5 days'
          days-before-stale: 30
          days-before-close: 5
          operations-per-run: 1500
          exempt-issue-labels: 'feature_request'
          exempt-pr-labels: 'feature_request'
          enable-statistics: 'true'
          close-issue-label: 'closed_for_stale'
          close-pr-label: 'closed_for_stale'
